### ISSUE TITLE
Callback methods?

### ISSUE THREAD

**Issue by KieranCarden** [maktoobgar/scene_manager#12]
Not really issue, but have no other way to ask questions.

Is there currently any way to initiate a callback after a transition has finished, or about to finish? Or a signal that is emitted after a transition has finished? There's a few scenarios I'm looking to trigger after a transition has finished and it would be useful if this was something built-in (if it's not already) rather than trying to work around it. Apologies in advance if this is already possible and I'm just overlooking it.

**Comment by maktoobgar** [comment]
Hello,

Your feature wasn't implemented, so I implemented it, use 3.6.0 version.
Wasn't a hard thing to do and didn't take a lot of time.
I hope it helps you throughout your projects.
You can see the list of all signals over [here](https://github.com/maktoobgar/scene_manager#signals) but I list them down here any way too:

1. `load_finished` => signal fires when interactively loading a scene finishes
1. `load_percent_changed(value: int)` => signal fires when interactively loading a scene progress percentage updates
1. `scene_changed` => signal fires when scene changes
1. `fade_in_started` => signal fires when fade in starts
1. `fade_out_started` => signal fires when fade out starts
1. `fade_in_finished` => signal fires when fade in finishes
1. `fade_out_finished` => signal fires when fade out finishes

The third one is the signal you need: `scene_changed`

**Comment by maktoobgar** [comment]
Plus since you mentioned "but have no other way to ask questions" I opened a discussion section for this repository.

**Comment by KieranCarden** [comment]
Oh wow, that's awesome! Thank you so much for adding this in, I appreciate it. Love the add-on btw. Extremely useful and powerful.
