### ISSUE TITLE
[BUG] Popup Menu offset is wrong in a 21:9 monitor 

### ISSUE THREAD

**Issue by JustusPan** [maktoobgar/scene_manager#13]
Version: v3.6.0
Godot: 4.1.1
![image](https://github.com/maktoobgar/scene_manager/assets/10916383/0c19aced-3f53-40ba-8e37-5bf7a2a46287)

**Comment by maktoobgar** [comment]
Hello.
Well... This is new.
I try to check this out by myself and see if that's the case still or not at the first free time that I can find.
Thank you for making an issue when there is an odd behavior.

**Comment by maktoobgar** [comment]
Hello again.
My friend, it seems fine here.
I can not replicate the bug in my own Laptop so...
If you can fix it up or at least tell me how to generate the bug, that would be helpful.

**Comment by maktoobgar** [comment]
One year has passed, I'm just gonna close this.
