### ISSUE TITLE
[Feature request] add a loading screen behavior configuration 

### ISSUE THREAD

**Issue by Supamiu** [maktoobgar/scene_manager#17]
Hi, first of all, thanks for this amazing addon, helps me a lot !

As you mentionned in your code examples, it's not that hard to add a loading screen, `change_scene` to your loading screen scene, then inside the loading screen, call `change_scene` again.

The issue with this is if the second scene is taking some time to load (like a procedurally generated world for instance), in which case you'll have the following:

 - Start scene
 - Transition to loading screen
 - Loading screen
 - Transition to black screen
  - Stays in black screen until scene is ready
 - Transition to target scene
 - Target scene is now current scene

I'm pretty new to Godot so I might be missing something obvious here but it looks like having the Loading screen add a given scene to the tree to then check when it's ready before triggering transition isn't possible, and that would be amazing as it'd allow for more detailed loading screen, showing data from the scene that's currently being set up.

**Comment by maktoobgar** [comment]
Hi,
First, I don't think you are missing something obvious, your case is just a little bit different than normal cases and that's because of procedural generating your world.
What I think you can do, if you really want to use this addon, is to just get a little bit deeper into this and I will help you through it.

1. You change the screen to loading screen.
2. You wait in the loading screen for the scene to load into the memory.
3. When the loading is finished and you get informed by `SceneManager.load_finished` signal, you don't change the scene to the new loaded scene by `SceneManager.change_scene_to_loaded_scene` but instead what you do, is that you will get the loaded scene by yourself from `SceneManager`like this:
```gdscript
if SceneManager._load_scene != "":
	var scene = ResourceLoader.load_threaded_get(SceneManager._load_scene) as PackedScene
	if scene:
		SceneManager._load_scene = ""
```
Now you have your scene in the `scene` variable.
**Note**: `SceneManager._load_scene = ""` line is important for scene manager, just let it be. and if you want to know where did I get these lines, I get them from `SceneManager.change_scene_to_loaded_scene` function.
4. Then after, let's add the scene to the tree and let it load the chunks without touching the current scene (which is the loading screen):
```gdscript
if SceneManager._load_scene != "":
	var scene = ResourceLoader.load_threaded_get(SceneManager._load_scene) as PackedScene
	if scene:
		SceneManager._load_scene = ""
		var root = get_tree().get_root()
		root.add_child(scene.instantiate())
```
5. That's it, we are still seeing the loading screen (If I'm not mistaken) and the game is silently generating the world in the background, now we wait for the world generation process to be done and after it is done, what you do is that you do the transaction by yourself using `SceneManager` singleton:
```gdscript
# this is literally the `SceneManager.change_scene` function but with little less complication considering you know what you're doing
func change_scene_by_hand_after_generating_the_world():
	SceneManager._set_in_transition()
	SceneManager._set_clickable(your_general_options.clickable)
	SceneManager._set_pattern(your_fade_out_options, your_general_options)
	# fade out transaction happens here
	if SceneManager._fade_out(your_fade_out_options.fade_speed):
		await SceneManager._animation_player.animation_finished
	# real change scene goes here
	var root = get_tree().get_root()
	# get the loaded, completely generated scene
	var scene = root.get_child(root.get_child_count() - 1)
	# delete the loaded scene
	root.get_child(root.get_child_count() - 2).free()
	# inform godot which now this is the current scene
	get_tree().set_current_scene(scene)
	# the change scene is done
	# now let's fade in
	SceneManager._animation_player.play(SceneManager.NO_COLOR, -1, 1, false)
	SceneManager._set_pattern(your_fade_in_options, your_general_options)
	if SceneManager._fade_in(your_fade_in_options.fade_speed):
		await SceneManager._animation_player.animation_finished
	SceneManager._set_clickable(true)
	SceneManager._set_out_transition()
```

And done.
Hope this helps.

**Comment by maktoobgar** [comment]
And at last, now that I'm looking at it, its not that complicated, if this works for you, I will add this into the addon later.
Keep me updated about this scenario please.

**Comment by Supamiu** [comment]
Thanks ! I'll check that once I have a bit of time for it and report the results here 👍

**Comment by Supamiu** [comment]
So I had to edit the code a bit, because I need a reference to the scene instance in order to know when it's ready to load (for this I have a signal provided by the root node of the instance that tells me when loading is done).

Here is my basic loading screen:

```gdscript
extends Control

@onready var label = $CenterContainer/HBoxContainer/Label

var no_fade = SceneManager.create_options(0.1, "", 0.1)
var pixel_fade = SceneManager.create_options(1.0, "pixel", 0.2, true)
var general_options = SceneManager.create_general_options(Color(0, 0, 0), 0, true, true)
	
func _ready():
	# TODO random message, better loading experience
	label.text = tr("LOADING:LOADING_DATA")
	var target = SceneManager.get_recorded_scene()
	SceneManager.load_scene_interactive(target)
	SceneManager.load_finished.connect(_init_target_scene)

func _init_target_scene():
	if SceneManager._load_scene != "":
		var scene = ResourceLoader.load_threaded_get(SceneManager._load_scene) as PackedScene
		if scene:
			SceneManager._load_scene = ""
			var root = get_tree().get_root()
			var instance = scene.instantiate()
			root.add_child(instance)
			instance.load_done.connect(change_scene_by_hand_after_generating_the_world)

func change_scene_by_hand_after_generating_the_world():
	SceneManager._set_in_transition()
	SceneManager._set_clickable(general_options.clickable)
	SceneManager._set_pattern(pixel_fade, general_options)
	# fade out transaction happens here
	if SceneManager._fade_out(no_fade.fade_speed):
		await SceneManager._animation_player.animation_finished
	# real change scene goes here
	var root = get_tree().get_root()
	# get the loaded, completely generated scene
	var scene = root.get_child(root.get_child_count() - 1)
	# delete the loaded scene
	root.get_child(root.get_child_count() - 2).free()
	# inform godot which now this is the current scene
	get_tree().set_current_scene(scene)
	# the change scene is done
	# now let's fade in
	SceneManager._animation_player.play(SceneManager.NO_COLOR, -1, 1, false)
	SceneManager._set_pattern(pixel_fade, general_options)
	if SceneManager._fade_in(pixel_fade.fade_speed):
		await SceneManager._animation_player.animation_finished
	SceneManager._set_clickable(true)
	SceneManager._set_out_transition()
```

But I'm getting an error at `get_tree().set_current_scene(scene)` that says "Cannot call method 'get_tree' on a previously freed instance". I assume this is because the loaded scene is being removed two lines before but idk if it's safe to remove that, I think you'll know better than me for sure.

**Comment by maktoobgar** [comment]
I'm gonna test this.
I'll be back.

**Comment by Supamiu** [comment]
Moving the `root.get_child(root.get_child_count() - 2).free()` call at the end of the function seems to be doing the job, as the loading screen then removes itself as the final operation 🙂

**Comment by maktoobgar** [comment]
I implemented this feature into [v3.8.0](https://github.com/maktoobgar/scene_manager/releases/tag/3.8.0) new release.
It wasn't hard to be honest, I was talking nonsense when I said it gets complicated if I add this feature.
Have a look at the methods section: https://github.com/maktoobgar/scene_manager#methods
The last two new functions are exactly for this scenario, function 23 and 24.
Documentation is updated and a new example is now available in the demo for exactly this scenario which the codes are available too and kinda described in here:
https://github.com/maktoobgar/scene_manager#more-complex-example-with-loading-screen-for-scenarios-that-scenes-need-some-time-in-background

And yeah, that's it.
If you want to see the implemented example which was kinda explained in the previously mentioned section of the readme, just take a look at the first new oddly named button in `scene3.tscn` and follow where that button leads you after:

![image](https://github.com/maktoobgar/scene_manager/assets/50152425/d3b0a96b-fe94-4d1d-b7b5-2a7804c5ba26)

And that's it.
If you found any bugs, or had any new ideas, please do tell.

**Comment by Supamiu** [comment]
I don't think it fixes the issue entirely but this is me not explaining everything properly I think.

So in my use case, the scene itself has signals to give me progress, so I can have my loading screen display different labels based on the generation step, helping for debugging and for UX purpose too.

So I'd say the only thing that the new methods are missing is to return the actual scene instance in `add_loaded_scene_to_scene_tree()` so we can easily connect any signal to it, or do other operations that one might want to do.

**Comment by maktoobgar** [comment]
Yeah, this is nice.
I will add this to the later versions too as soon as I found time to do that and I'll inform you about the new version with that change also.
For now just changing the current `add_loaded_scene_to_scene_tree` function code to what you just wrote will satisfy your needs as you just said.
Just one thing as a suggestion, change `Variant` return type to `Node`.
That's it.
Thank you for this nice issue.
