### ISSUE TITLE
[Bug] Possible threadlock when using load_scene_interactive()

### ISSUE THREAD

**Issue by DerLeole** [maktoobgar/scene_manager#19]
The `load_scene_interactive()` method of the SceneManager is hardcorded to use `use_sub_threads = true` when calling `ResourceLoader.load_threaded_request()`. In the newest versions of Godot there seems to be a bug that can cause a threadlock in the resource loader that will result in infinite loading of the scene without any error.

This is likely cause by use of the preload() function shortly prior to or at the same time as `ResourceLoader.load_threaded_request()` with `use_sub_threads = true`.

See the following two GitHub issues:
https://github.com/godotengine/godot/issues/85255
https://github.com/godotengine/godot/issues/84012

It would be cool to add a warning somewhere in the scene manager documentation about it until its fixed and maybe give the option to set `use_sub_threads = false` when calling `load_scene_interactive()`.

Thank you very much, this plugin is awesome!

**Comment by faceze** [comment]
This seems to be the reason why I couldn't load my scene beyond the 70% mark.
