### ISSUE TITLE
show_first_scene(): Scene is briefly visible

### ISSUE THREAD

**Issue by NickHatBoecker** [maktoobgar/scene_manager#20]
My first scene configured is "StartMenu".
Inside of this scene I have a node "GameStart". This node has a Script "GameStart.gd" with the following contents:

```gdscript
extends Node


## This is no real script.
## It is only used to fade in first game scene.
func _ready() -> void:
    var fadeIn = SceneManager.create_options(10, "fade", 0.1, false)
    var options = SceneManager.create_general_options("black", 0.0, false, true)
    SceneManager.show_first_scene(fadeIn, options)
```

When I click on Play the StartMenu scene is visible for like half a seconds and then it smoothly fades in.
I this the desired behavior or am I doing something wrong? I thought the first scene should not be visible before fading in.

**Comment by maktoobgar** [comment]
Hello, it seems like in your scenario, ready function is getting called so late so that the first scene is getting shown for a small time.
What I can suggest is that instead of running those three lines in `_ready` function, run them in `_tree_entered` and see if anything changes and it works as expected or not.
Keep me posted.

**Comment by NickHatBoecker** [comment]
There is no `_tree_entered` func, at least not in Godot 4. But I tried `_enter_tree()`. With this I dont see any fade at all.
I found a workaround: Use ColorRect instead of Node, set its color to black and use the updated code:

```gdscript
extends ColorRect


func _enter_tree() -> void:
    z_index = 100


func _ready() -> void:
    await get_tree().create_timer(2).timeout
    z_index = 0

    var fadeIn = SceneManager.create_options(1, "fade", 0.1, false)
    var options = SceneManager.create_general_options("black", 0.0, false, true)
    SceneManager.show_first_scene(fadeIn, options)
```

**Comment by maktoobgar** [comment]
Hi again, `_enter_tree()` is exactly what I meant by that I just thought `_tree_entered` was the name of it, sorry for my poor English. I just understood what I wrote and I'm laughing while typing this. XD

Anyway, Back to the problem, if you think this is ok and fixes your problem for now, good, but if you are interested in helping to find out what is the problem, you can provide me with a scenario which this behavior happens in it and I can check that project out and find out what is going wrong in the addon and fix it.
Inform me if you made a repository for this purpose.

**Comment by NickHatBoecker** [comment]
No problem :) Was easy enough to find the function name with your hint 👍

To be honest, I think it's a godot problem. Because sometimes even the workaround doesn't work, sometimes it does.
So I will close here :)
