### ISSUE TITLE
Warnings on load, invalid UIDs - using text paths instead

### ISSUE THREAD

**Issue by snewell92** [maktoobgar/scene_manager#24]
Hi, unsure what's the problem, but I have a bunch of warnings on load

![image](https://github.com/maktoobgar/scene_manager/assets/25957964/c5aaddac-4894-4886-af2d-b718d154cea0)

<details><summary>Copy Pasta</summary>

```
Godot Engine v4.2.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
Add Autoload
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/menu.tscn:3 - ext_resource, invalid UID: uid://cnhtsuf78gsy7 - using text path instead: res://addons/scene_manager/icons/GuiChecked.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/menu.tscn:5 - ext_resource, invalid UID: uid://bt1mtu3gbmwqc - using text path instead: res://addons/scene_manager/icons/FileDialog.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/ignore_item.tscn:3 - ext_resource, invalid UID: uid://dw322nmqpqwfq - using text path instead: res://addons/scene_manager/icons/ImportFail.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/scene_item.tscn:4 - ext_resource, invalid UID: uid://brxxaey30q7uk - using text path instead: res://addons/scene_manager/icons/GuiTabMenuHl.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/scene_item.tscn:6 - ext_resource, invalid UID: uid://b4xi5nvjb3rhr - using text path instead: res://addons/scene_manager/icons/PlayOverlay.png
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/sub_section.tscn:4 - ext_resource, invalid UID: uid://dsgnkxtiko66g - using text path instead: res://addons/scene_manager/icons/GuiOptionArrowRight.png
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/sub_section.tscn:6 - ext_resource, invalid UID: uid://dw322nmqpqwfq - using text path instead: res://addons/scene_manager/icons/ImportFail.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/scene_list.tscn:4 - ext_resource, invalid UID: uid://dw322nmqpqwfq - using text path instead: res://addons/scene_manager/icons/ImportFail.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/scene_manager/scene_list.tscn:5 - ext_resource, invalid UID: uid://d250i5cu8lgbd - using text path instead: res://addons/scene_manager/icons/eye_open.png
Add Autoload
Add Autoload
Following a PhysicsBody2D node will likely result in jitter - on lower physics ticks in particular.
Once Godot 4.3 is released, will strongly recommend upgrading to that as it has built-in support for 2D Physics Interpolation.
Until then, try following the guide on the documentation site for better results.
This tip can be disabled from within Project Settings / Phantom Camera / Tips / Show Jitter Tips
```
</details>

**Comment by maktoobgar** [comment]
Hello,
Thanks for taking your time to open an issue when observed an odd behavior.
Sorry to answer so late too, I just don't have free time right now.
I will come at this about 2 weeks later and will fix it hopefully.

**Comment by JelmerBerghs** [comment]
I have the same problem:
![image](https://github.com/maktoobgar/scene_manager/assets/22679293/4e602e4b-df8c-4bf4-9458-598d5257deb8)

**Comment by maktoobgar** [comment]
Hi again,
I checked out this log message and it seems to be a Godot logging problem from these issues:
https://github.com/godotengine/godot/issues/64881
https://github.com/dialogic-godot/dialogic/issues/1155

And it seems like others are having the same problem.
If any solutions found, I will fix this with the solution but it seems like in the new Godot version the problem will be gone hopefully.

**Comment by soeren-spindler** [comment]
I was running into these warning using **Godot Engine v4.3.beta3**.
After reading through some related issues, I found out that it's indeed pointing to some invalid UIDs.

The problems can be solved by opening the scenes with invalid UIDs in Godot Editor (in my case 4.3beta3) and saving them again.

Can't explain the details but saving the scenes seems to fix the UIDs and the warnings are gone 🥳

**Comment by substract** [comment]
![uid_problem](https://github.com/user-attachments/assets/5ac10f04-9c5c-442c-acaa-9ae88a1826bc)

Hi, I had the same problem, too when updating my project to Godot 4.3 rc3.
Mostly materials (textures) in particles were affected. Deleting the import file of the texture didn't help. Not even assigning a completely new texture to the material did help, according to the warning message now the new texture has the invalid UID.

After a lot of trying around I tried something with success: 
go into the material settings, to the albedo/ texture input and make the texture unique (see screenshot). Don't forget to save.
In my case doing that solved the problem!

**Comment by maktoobgar** [comment]
Hi again,
Thanks for the solution @substract.
I can't replicate this situation on my end, please report if it is still the case in Godot 4.3 or it's fixed.
@snewell92 @JelmerBerghs @soeren-spindler

**Comment by LowPolyMike** [comment]
Just to confirm it happened to me in Godot 4.3 with some textures of a theme for a project I'm working on.

@substract solution fixed it.

**Comment by maktoobgar** [comment]
At this point, I don't know if we should close this and accept @substract 's answer or not.

**Comment by soeren-spindler** [comment]
Created a fresh project with 4.3. 
No warning so far.

**Comment by maktoobgar** [comment]
Thanks @soeren-spindler 
If it is fixed in fresh projects and others can fix by [substract](https://github.com/maktoobgar/scene_manager/issues/24#issuecomment-2282650381)'s answer, I think it's better to close this now.
Thanks everyone. 🙏

**Comment by TinyTakinTeller** [comment]
I get these warnings when doing a clean checkout of my Godot 4.3 project that uses this plugin.

The [subtract's workaround](https://github.com/maktoobgar/scene_manager/issues/24#issuecomment-2282650381) works, but it will be annyoing if this has to be done after every clean checkout.

**Comment by soeren-spindler** [comment]
They announced changes to the UIDs. Without diving into details it might help solving this problem since it's connected.

https://godotengine.org/article/uid-changes-coming-to-godot-4-4

Will try with 4.4 when I got some time

**Comment by TinyTakinTeller** [comment]
Should delete `.gitignore` from /icons: 
- https://github.com/maktoobgar/scene_manager/blob/main/addons/scene_manager/icons/.gitignore

Because `.import` files should not be ignored as they contain UID information

EDIT: https://github.com/maktoobgar/scene_manager/pull/43
