### ISSUE TITLE
Identifier "Scenes" not declared in the current scope.

### ISSUE THREAD

**Issue by MasonGuinn** [maktoobgar/scene_manager#26]

**Comment by MasonGuinn** [comment]
So, I deleted everything and restarted. I found the issue. For some reason, "Scenes" in Autoload was not there. Restarting fixed this and I have it working. Amazing stuff.

**Comment by maktoobgar** [comment]
Hello,
No problem man, thanks for taking your time to open an issue when observed an odd behavior and do it again if you see fit.
Plus, you don't need to delete an issue, (there is no delete mechanic for issues to be honest) just close it and say in a comment that problem fixed, and... that's wrap.
Have a good day.
