### ISSUE TITLE
Endless loading and Godot not responding after fixing ignored scenes

### ISSUE THREAD

**Issue by NickHatBoecker** [maktoobgar/scene_manager#30]
After https://github.com/maktoobgar/scene_manager/issues/23 was solved (thank you so much for this!), I downloaded the current main branch. I opened my project and got a lot of errors and the scene manager window was empty. I just closed it and reopened it again. Now the errors were gone and the window displayed my scenes.

But I get a loading cursor and MacOS reports the app as "not responding". So I cannot work on the project.
I restored the previous version of scene manager I used (3.8.0) and it immediately works again.

Unfortunately no error message is displayed, so I don't know what could cause the problem.

**Comment by maktoobgar** [comment]
Hi,
Thanks again.
Can you install the new version on your project again please and report the error logs you get afterwards?
That would be helpful so that I could have a lead to go based of of.

**Comment by NickHatBoecker** [comment]
Will surely do, but I don't know where to find the error logs 🙈 Can you give me a hint?

**Comment by maktoobgar** [comment]
Sure.

![image](https://github.com/maktoobgar/scene_manager/assets/50152425/8e57a26b-8235-41b7-b6f6-af70fd38d378)
Just copy content of `output` window which hopefully has a lot of error messages.

**Comment by maktoobgar** [comment]
I'm gonna close this for now because one month has passed from our last conversation.
If you came back to it, I'll open it again.

**Comment by adadgio** [comment]
Hi, on MacOS, I have exactly the same problem as soos as I activate the plugin, Godot Loads indefinately and crashed after a while (to the point I dont have time to go to the error log). Does it scan the whole project on load ?
