### ISSUE TITLE
Loading scenes crashing in Godot 4.3

### ISSUE THREAD

**Issue by KieranCarden** [maktoobgar/scene_manager#32]
I'm attempting to utilize the loading or loading with initialization setups, and both are always falling into the `"Scene Manager Error: for some reason, loading failed, I don't know why` condition. The demo project has the same issue.

I tested the demo project in 4.2 and both loading setups work, so it seems like something in 4.3 has changed and is affecting the way loading is currently written.

**Comment by maktoobgar** [comment]
Hello,
Reported this issue, hopefully they fix it soon.

**Comment by maktoobgar** [comment]
Well, They did fix it...
That was fast.
I'll reopen this if the problem in the new version still exists.

**Comment by KieranCarden** [comment]
Awesome! Thanks for sending it that way.

**Comment by KieranCarden** [comment]
Just wanted to update here, the fix is in place for the full release of 4.3 and working as expected again :D
