### ISSUE TITLE
Newer files on disk

### ISSUE THREAD

**Issue by KieranCarden** [maktoobgar/scene_manager#33]
I'm not necessarily sure if this is an issue of the addon or something 4.3 is doing, or maybe something weird in my project, but whenever I start my game and then close it this prompt comes up:
![newer_disk](https://github.com/user-attachments/assets/aeb755a6-cd89-4c8e-a8bc-8b7288a9cda7)

It also seems to do it when focusing a window other than Godot, then focusing back into Godot. This happens even if I've never started my game, just after opening the project.

~I can't seem to recreate it with the demo project, but I'm using the same setup that the "loading with initialization" setup is using from the demo so I'm not entirely sure what is going on.~

I can recreate it in the demo project. When you add a new "ignores" folder/directory, it will start to cause the same prompt in both of the situations outlined above. Seems like 4.3 doesn't like that the scenes.gd file gets changed.

Choosing "Discard local changes and reload" in the demo project seems to make it go away until adding a new folder to the ignores list, then it will happen again.

Edit: I think I found the culprit. I had Auto Save checked and I'm guessing that auto save happens in certain scenarios, or seems to be at least. Turning that off and manually hitting Save will cause the prompt but only one time after clicking it. Selecting "Discard local changes and reload" after hitting "Save" in the plugin does "solve" it, though I imagine this will be an annoying thing for people to deal with (not the addon fault).

Can probably close this if it's not a thing the addon can solve for.

**Comment by maktoobgar** [comment]
Hi,
I did test this out and it seems like it doesn't happen unless you have a tab open for `scenes.gd` file like in the image below.
![image_2024-08-17_09-38-05](https://github.com/user-attachments/assets/d41a3dce-3378-469d-98bd-889d5afec2d2)
All you need to do is to close that `scenes.gd` tab with right click and then click on close to get rid of those messages.
If that works, just inform me to close this issue.

**Comment by KieranCarden** [comment]
Interesting. Closing that (not sure why I had it open in the first place) did make it so the prompt doesn't happen. False alarm I suppose, that's my bad.

Feel free to close this.

**Comment by maktoobgar** [comment]
Please keep reporting whatever bug or weird behavior you find. Issues keep the project alive.
Doesn't matter if one or two of them are not actual bugs.
Thanks for reporting issues. ❤️
