### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by RavenousMonk** [maktoobgar/scene_manager#7]
Hey, there.  Do you have a more detailed explanation of how to use this addon somewhere?  Or a youtube video?  I've installed it and assigned some of my scenes as Character, Menu, and created a new Category "Districts" for my maps.  But I'm trying to assign a Subcategory.  I've created one called Pois, but I can't add anything to it or use it at all.

**Comment by maktoobgar** [comment]
Try drag and drop my friend.
Drag and then drop on the title of your subcategory, That will do the trick.

Sorry to not have a Youtube video for this tool, I just don't have enough time as I had before.

Keep me updated here if there was any other issues.
I'll be your Youtube video for now. 😅
