### ISSUE TITLE
"Scene Manager Error: loaded scene is not defined in scene manager tool."

### ISSUE THREAD

**Issue by ca3gamedev** [maktoobgar/scene_manager#8]
Doesnt matter what I do, this error runs before my first scene ready function.

No amount of copying the demo files or documentation script, matters.
It always run before the _ready of the first scene.

**Comment by maktoobgar** [comment]
You need to save your scenes.
Simply just save all your scenes once.
All that says is: I can't manage this scene because I don't have this scene in my scenes list.

![image](https://github.com/maktoobgar/scene_manager/assets/50152425/7a600cdb-e5bf-4045-87b4-dd4698e56084)
